config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'students#index'
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
  	@students = Student.all
  end

  def new
  	@student = Student.new
  end

  def create
  	Student.create(student_params)
  	redirect_to root_path
  end

  private
  def student_params
    params.require(:student).permit(:FirstName, :LastName, :skypeID)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Careconnect</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <%= link_to 'CareConnect', root_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_student_path, class: 'nav-link' do %>
              <i class="fa fa-plus-circle"></i>
              New Student
            <% end %>
          </li>
        </ul>
      </div>
    </nav>

	<% if notice.present? %>
	  <p class="alert alert-info"><%= notice %></p>
	<% end %>
	<% if alert.present? %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>

    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<% @students.each do |student| %>
  <div class="booyah-box  col-10 offset-1">
    <h1><%= student.FirstName %></h1><br />
    <p><%= student.skypeID %></p><br />
  </div>

  <hr />
<% end %>

app/views/students/new.html.erb
<div class="booyah-box col-10 offset-1">
	<h1>Enter Your Student Details</h1>
	<%= simple_form_for @student do |f| %>
      <%= f.input :FirstName %>
      <%= f.input :LastName %>
      <%= f.input :skypeID %>
      <br />
      <%= f.submit 'Create', class: 'btn btn-primary' %>
    <% end %>
</div>